; Generated by CC-Project Compiler
include Irvine32.inc
.data
_x DWORD 0
_dx DWORD 0
t0 DWORD 0
t1 DWORD 0
t2 DWORD 0
t3 DWORD 0
t4 DWORD 0
t5 DWORD 0
t6 DWORD 0
t7 DWORD 0
t8 DWORD 0
t9 DWORD 0
t10 DWORD 0
t11 DWORD 0
t12 DWORD 0
t13 DWORD 0
t14 DWORD 0
t15 DWORD 0
t16 DWORD 0
t17 DWORD 0
t18 DWORD 0
t19 DWORD 0
t20 DWORD 0
.code
main PROC
    mov eax, 10
    mov t0, eax
    mov eax, t0
    mov _x, eax
    mov eax, 1
    mov t1, eax
    mov eax, t1
    mov _dx, eax
    mov eax, 50
    mov t2, eax
    mov eax, 0
    mov t3, eax
L0:
    mov eax, t3
    sub eax, t2
    mov t4, eax
    cmp t4, 0
    je L1
    call ClrScr
    mov eax, 10
    mov t5, eax
    mov eax, 4
    mov t6, eax
    mov eax, 4
    mov t7, eax
    mov eax, 15
    mov t8, eax
    push _x
    push t5
    push t6
    push t7
    push t8
    call DrawRect_helper
    mov eax, _x
    add eax, _dx
    mov t9, eax
    mov eax, t9
    mov _x, eax
    mov eax, 30
    mov t10, eax
    mov eax, _x
    cmp eax, t10
    mov t11, 0
    jg L_cmp_t11
    mov t11, 1
L_cmp_t11:
    cmp t11, 0
    je L2
    mov eax, 0
    mov t12, eax
    mov eax, 1
    mov t13, eax
    mov eax, t12
    sub eax, t13
    mov t14, eax
    mov eax, t14
    mov _dx, eax
    jmp L3
L2:
L3:
    mov eax, 2
    mov t15, eax
    mov eax, _x
    cmp eax, t15
    mov t16, 0
    jl L_cmp_t16
    mov t16, 1
L_cmp_t16:
    cmp t16, 0
    je L4
    mov eax, 1
    mov t17, eax
    mov eax, t17
    mov _dx, eax
    jmp L5
L4:
L5:
    mov eax, 50
    mov t18, eax
    mov eax, t18
    call Delay
    mov eax, 1
    mov t19, eax
    mov eax, t3
    add eax, t19
    mov t20, eax
    mov eax, t20
    mov t3, eax
    jmp L0
L1:
    call ReadChar
    exit
main ENDP

DrawPixel_helper PROC
    push ebp
    mov ebp, esp
    mov dh, byte ptr [ebp+12]
    mov dl, byte ptr [ebp+8]
    call Gotoxy
    mov al, '*'
    call WriteChar
    pop ebp
    ret 12
DrawPixel_helper ENDP

DrawRect_helper PROC
    push ebp
    mov ebp, esp
    mov ecx, [ebp+16]
    mov esi, [ebp+12]
    mov dh, byte ptr [ebp+20]
row_loop:
    push ecx
    mov dl, byte ptr [ebp+24]
    mov ecx, esi
col_loop:
    push ecx
    call Gotoxy
    mov al, '#'
    call WriteChar
    inc dl
    pop ecx
    loop col_loop
    inc dh
    pop ecx
    loop row_loop
    pop ebp
    ret 20
DrawRect_helper ENDP

END main
