; Generated by CC-Project Compiler
include Irvine32.inc
.data
_row DWORD 0
_col DWORD 0
t0 DWORD 0
t1 DWORD 0
t2 DWORD 0
t3 DWORD 0
t4 DWORD 0
t5 DWORD 0
t6 DWORD 0
t7 DWORD 0
t8 DWORD 0
t9 DWORD 0
t10 DWORD 0
t11 DWORD 0
t12 DWORD 0
t13 DWORD 0
t14 DWORD 0
t15 DWORD 0
t16 DWORD 0
t17 DWORD 0
t18 DWORD 0
t19 DWORD 0
.code
main PROC
    mov eax, 0
    mov t0, eax
    mov eax, t0
    mov _row, eax
    mov eax, 8
    mov t1, eax
    mov eax, 0
    mov t2, eax
L0:
    mov eax, t2
    sub eax, t1
    mov t3, eax
    cmp t3, 0
    je L1
    mov eax, 0
    mov t4, eax
    mov eax, t4
    mov _col, eax
    mov eax, 8
    mov t5, eax
    mov eax, 0
    mov t6, eax
L2:
    mov eax, t6
    sub eax, t5
    mov t7, eax
    cmp t7, 0
    je L3
    mov eax, _row
    sub eax, _col
    mov t8, eax
    mov eax, 0
    mov t9, eax
    mov eax, t8
    cmp eax, t9
    mov t10, 0
    jg L_cmp_t10
    mov t10, 1
L_cmp_t10:
    cmp t10, 0
    je L4
    mov eax, 1
    mov t11, eax
    push _col
    push _row
    push t11
    call DrawPixel_helper
    jmp L5
L4:
L5:
    mov eax, 1
    mov t12, eax
    mov eax, _col
    add eax, t12
    mov t13, eax
    mov eax, t13
    mov _col, eax
    mov eax, 1
    mov t14, eax
    mov eax, t6
    add eax, t14
    mov t15, eax
    mov eax, t15
    mov t6, eax
    jmp L2
L3:
    mov eax, 1
    mov t16, eax
    mov eax, _row
    add eax, t16
    mov t17, eax
    mov eax, t17
    mov _row, eax
    mov eax, 1
    mov t18, eax
    mov eax, t2
    add eax, t18
    mov t19, eax
    mov eax, t19
    mov t2, eax
    jmp L0
L1:
    call ReadChar
    exit
main ENDP

DrawPixel_helper PROC
    push ebp
    mov ebp, esp
    mov dh, byte ptr [ebp+12]
    mov dl, byte ptr [ebp+8]
    call Gotoxy
    mov al, '*'
    call WriteChar
    pop ebp
    ret 12
DrawPixel_helper ENDP

DrawRect_helper PROC
    push ebp
    mov ebp, esp
    mov ecx, [ebp+16]
    mov esi, [ebp+12]
    mov dh, byte ptr [ebp+20]
row_loop:
    push ecx
    mov dl, byte ptr [ebp+24]
    mov ecx, esi
col_loop:
    push ecx
    call Gotoxy
    mov al, '#'
    call WriteChar
    inc dl
    pop ecx
    loop col_loop
    inc dh
    pop ecx
    loop row_loop
    pop ebp
    ret 20
DrawRect_helper ENDP

END main
