; Generated by CC-Project Compiler
include Irvine32.inc
.data
_x DWORD 0
_y DWORD 0
t0 DWORD 0
t1 DWORD 0
t2 DWORD 0
t3 DWORD 0
t4 DWORD 0
.code
main PROC
    mov eax, 5
    mov t0, eax
    mov eax, t0
    mov _x, eax
    mov eax, 10
    mov t1, eax
    mov eax, t1
    mov _y, eax
    call ClrScr
    mov eax, 4
    mov t2, eax
    mov eax, 4
    mov t3, eax
    mov eax, 15
    mov t4, eax
    push _x
    push _y
    push t2
    push t3
    push t4
    call DrawRect_helper
    call ReadChar
    exit
main ENDP

DrawPixel_helper PROC
    push ebp
    mov ebp, esp
    mov dh, byte ptr [ebp+12]
    mov dl, byte ptr [ebp+8]
    call Gotoxy
    mov al, '*'
    call WriteChar
    pop ebp
    ret 12
DrawPixel_helper ENDP

DrawRect_helper PROC
    push ebp
    mov ebp, esp
    mov ecx, [ebp+16]
    mov esi, [ebp+12]
    mov dh, byte ptr [ebp+20]
row_loop:
    push ecx
    mov dl, byte ptr [ebp+24]
    mov ecx, esi
col_loop:
    push ecx
    call Gotoxy
    mov al, '#'
    call WriteChar
    inc dl
    pop ecx
    loop col_loop
    inc dh
    pop ecx
    loop row_loop
    pop ebp
    ret 20
DrawRect_helper ENDP

END main
