; Generated by CC-Project Compiler
include Irvine32.inc
.data
_x DWORD 0
_y DWORD 0
t0 DWORD 0
t1 DWORD 0
t2 DWORD 0
t3 DWORD 0
t4 DWORD 0
t5 DWORD 0
t6 DWORD 0
t7 DWORD 0
t8 DWORD 0
t9 DWORD 0
t10 DWORD 0
t11 DWORD 0
t12 DWORD 0
.code
main PROC
    mov eax, 0
    mov t0, eax
    mov eax, t0
    mov _x, eax
    mov eax, 0
    mov t1, eax
    mov eax, t1
    mov _y, eax
    mov eax, 20
    mov t2, eax
    mov eax, 0
    mov t3, eax
L0:
    mov eax, t3
    sub eax, t2
    mov t4, eax
    cmp t4, 0
    je L1
    mov eax, 1
    mov t5, eax
    push _x
    push _y
    push t5
    call DrawPixel_helper
    mov eax, 1
    mov t6, eax
    mov eax, _x
    add eax, t6
    mov t7, eax
    mov eax, t7
    mov _x, eax
    mov eax, 1
    mov t8, eax
    mov eax, _y
    add eax, t8
    mov t9, eax
    mov eax, t9
    mov _y, eax
    mov eax, 50
    mov t10, eax
    mov eax, t10
    call Delay
    mov eax, 1
    mov t11, eax
    mov eax, t3
    add eax, t11
    mov t12, eax
    mov eax, t12
    mov t3, eax
    jmp L0
L1:
    call ReadChar
    exit
main ENDP

DrawPixel_helper PROC
    push ebp
    mov ebp, esp
    mov dh, byte ptr [ebp+12]
    mov dl, byte ptr [ebp+8]
    call Gotoxy
    mov al, '*'
    call WriteChar
    pop ebp
    ret 12
DrawPixel_helper ENDP

DrawRect_helper PROC
    push ebp
    mov ebp, esp
    mov ecx, [ebp+16]
    mov esi, [ebp+12]
    mov dh, byte ptr [ebp+20]
row_loop:
    push ecx
    mov dl, byte ptr [ebp+24]
    mov ecx, esi
col_loop:
    push ecx
    call Gotoxy
    mov al, '#'
    call WriteChar
    inc dl
    pop ecx
    loop col_loop
    inc dh
    pop ecx
    loop row_loop
    pop ebp
    ret 20
DrawRect_helper ENDP

END main
