; Generated by CC-Project Compiler
include Irvine32.inc
.data
_size DWORD 0
_dx DWORD 0
_x DWORD 0
_y DWORD 0
t0 DWORD 0
t1 DWORD 0
t2 DWORD 0
t3 DWORD 0
t4 DWORD 0
t5 DWORD 0
t6 DWORD 0
t7 DWORD 0
t8 DWORD 0
t9 DWORD 0
t10 DWORD 0
t11 DWORD 0
t12 DWORD 0
t13 DWORD 0
t14 DWORD 0
t15 DWORD 0
t16 DWORD 0
t17 DWORD 0
t18 DWORD 0
t19 DWORD 0
.code
main PROC
    mov eax, 1
    mov t0, eax
    mov eax, t0
    mov _size, eax
    mov eax, 1
    mov t1, eax
    mov eax, t1
    mov _dx, eax
    mov eax, 20
    mov t2, eax
    mov eax, t2
    mov _x, eax
    mov eax, 12
    mov t3, eax
    mov eax, t3
    mov _y, eax
    mov eax, 40
    mov t4, eax
    mov eax, 0
    mov t5, eax
L0:
    mov eax, t5
    sub eax, t4
    mov t6, eax
    cmp t6, 0
    je L1
    call ClrScr
    mov eax, 15
    mov t7, eax
    push _x
    push _y
    push _size
    push _size
    push t7
    call DrawRect_helper
    mov eax, _size
    add eax, _dx
    mov t8, eax
    mov eax, t8
    mov _size, eax
    mov eax, 10
    mov t9, eax
    mov eax, _size
    cmp eax, t9
    mov t10, 0
    jg L_cmp_t10
    mov t10, 1
L_cmp_t10:
    cmp t10, 0
    je L2
    mov eax, 0
    mov t11, eax
    mov eax, 1
    mov t12, eax
    mov eax, t11
    sub eax, t12
    mov t13, eax
    mov eax, t13
    mov _dx, eax
    jmp L3
L2:
L3:
    mov eax, 1
    mov t14, eax
    mov eax, _size
    cmp eax, t14
    mov t15, 0
    jl L_cmp_t15
    mov t15, 1
L_cmp_t15:
    cmp t15, 0
    je L4
    mov eax, 1
    mov t16, eax
    mov eax, t16
    mov _dx, eax
    jmp L5
L4:
L5:
    mov eax, 100
    mov t17, eax
    mov eax, t17
    call Delay
    mov eax, 1
    mov t18, eax
    mov eax, t5
    add eax, t18
    mov t19, eax
    mov eax, t19
    mov t5, eax
    jmp L0
L1:
    call ReadChar
    exit
main ENDP

DrawPixel_helper PROC
    push ebp
    mov ebp, esp
    mov dh, byte ptr [ebp+12]
    mov dl, byte ptr [ebp+8]
    call Gotoxy
    mov al, '*'
    call WriteChar
    pop ebp
    ret 12
DrawPixel_helper ENDP

DrawRect_helper PROC
    push ebp
    mov ebp, esp
    mov ecx, [ebp+16]
    mov esi, [ebp+12]
    mov dh, byte ptr [ebp+20]
row_loop:
    push ecx
    mov dl, byte ptr [ebp+24]
    mov ecx, esi
col_loop:
    push ecx
    call Gotoxy
    mov al, '#'
    call WriteChar
    inc dl
    pop ecx
    loop col_loop
    inc dh
    pop ecx
    loop row_loop
    pop ebp
    ret 20
DrawRect_helper ENDP

END main
