use crate::ir::IRInst;
use crate::ast::{BinOp, CompareOp};
use std::collections::HashMap;
use anyhow::Result;
use std::fs;

#[allow(dead_code)]
pub struct X86Generator {
    data_vars: HashMap<String, i32>,
    next_label: u32,
}

impl X86Generator {
    pub fn new() -> Self {
        Self {
            data_vars: HashMap::new(),
            next_label: 0,
        }
    }

    // Mangle variable names: prefix with '_' to avoid MASM reserved words
    fn mangle(&self, name: &str) -> String {
        format!("_{}", name)
    }

    pub fn generate(&mut self, ir: Vec<IRInst>, output_path: &str) -> Result<()> {
        let mut asm = String::new();

        asm.push_str("; Generated by CC-Project Compiler\n");
        asm.push_str("include Irvine32.inc\n");
        asm.push_str(".data\n");

        // Collect user variables (not temporaries)
        let mut vars = Vec::new();
        for inst in &ir {
            if let IRInst::Copy(dest, _) = inst {
                if !vars.contains(dest) && !dest.starts_with('t') {
                    vars.push(dest.clone());
                }
            } else if let IRInst::LoadConst(dest, _) = inst {
                if !vars.contains(dest) && !dest.starts_with('t') {
                    vars.push(dest.clone());
                }
            }
        }
        for var in &vars {
            let mangled = self.mangle(var);
            asm.push_str(&format!("{} DWORD 0\n", mangled));
        }

        // Collect temporaries (t0, t1, ...)
        let mut temps = Vec::new();
        for inst in &ir {
            match inst {
                IRInst::LoadConst(dest, _)
                | IRInst::Copy(dest, _)
                | IRInst::BinOp(dest, _, _, _)
                | IRInst::Compare(dest, _, _, _) => {
                    if dest.starts_with('t') && !temps.contains(dest) {
                        temps.push(dest.clone());
                    }
                }
                IRInst::DrawPixel(x, y, c) => {
                    for var in [x, y, c] {
                        if var.starts_with('t') && !temps.contains(var) {
                            temps.push(var.clone());
                        }
                    }
                }
                IRInst::DrawRect(x, y, w, h, c) => {
                    for var in [x, y, w, h, c] {
                        if var.starts_with('t') && !temps.contains(var) {
                            temps.push(var.clone());
                        }
                    }
                }
                _ => {}
            }
        }
        for temp in &temps {
            asm.push_str(&format!("{} DWORD 0\n", temp));
        }

        asm.push_str(".code\n");
        asm.push_str("main PROC\n");

        for inst in ir {
            asm.push_str(&self.emit_inst(inst));
        }

        asm.push_str("    exit\n");
        asm.push_str("main ENDP\n\n");

        // Drawing helpers (real implementation)
        asm.push_str("DrawPixel_helper PROC\n");
        asm.push_str("    push ebp\n");
        asm.push_str("    mov ebp, esp\n");
        asm.push_str("    mov dh, byte ptr [ebp+12]\n");
        asm.push_str("    mov dl, byte ptr [ebp+8]\n");
        asm.push_str("    call Gotoxy\n");
        asm.push_str("    mov al, '*'\n");
        asm.push_str("    call WriteChar\n");
        asm.push_str("    pop ebp\n");
        asm.push_str("    ret 12\n");
        asm.push_str("DrawPixel_helper ENDP\n\n");

        asm.push_str("DrawRect_helper PROC\n");
        asm.push_str("    push ebp\n");
        asm.push_str("    mov ebp, esp\n");
        asm.push_str("    mov ecx, [ebp+16]\n");
        asm.push_str("    mov esi, [ebp+12]\n");
        asm.push_str("    mov dh, byte ptr [ebp+20]\n");
        asm.push_str("row_loop:\n");
        asm.push_str("    push ecx\n");
        asm.push_str("    mov dl, byte ptr [ebp+24]\n");
        asm.push_str("    mov ecx, esi\n");
        asm.push_str("col_loop:\n");
        asm.push_str("    push ecx\n");
        asm.push_str("    call Gotoxy\n");
        asm.push_str("    mov al, '#'\n");
        asm.push_str("    call WriteChar\n");
        asm.push_str("    inc dl\n");
        asm.push_str("    pop ecx\n");
        asm.push_str("    loop col_loop\n");
        asm.push_str("    inc dh\n");
        asm.push_str("    pop ecx\n");
        asm.push_str("    loop row_loop\n");
        asm.push_str("    pop ebp\n");
        asm.push_str("    ret 20\n");
        asm.push_str("DrawRect_helper ENDP\n\n");

        asm.push_str("END main\n");
        fs::write(output_path, asm)?;
        Ok(())
    }

    fn emit_inst(&mut self, inst: IRInst) -> String {
        match inst {
            IRInst::LoadConst(dest, val) => {
                let dest_mangled = if dest.starts_with('t') { dest.clone() } else { self.mangle(&dest) };
                format!("    mov eax, {}\n    mov {}, eax\n", val, dest_mangled)
            }
            IRInst::Copy(dest, src) => {
                let dest_mangled = if dest.starts_with('t') { dest.clone() } else { self.mangle(&dest) };
                let src_mangled = if src.starts_with('t') { src } else { self.mangle(&src) };
                format!("    mov eax, {}\n    mov {}, eax\n", src_mangled, dest_mangled)
            }
            IRInst::BinOp(dest, op, left, right) => {
                let dest_mangled = if dest.starts_with('t') { dest.clone() } else { self.mangle(&dest) };
                let left_mangled  = if left.starts_with('t')  { left } else { self.mangle(&left) };
                let right_mangled = if right.starts_with('t') { right } else { self.mangle(&right) };
                let op_asm = match op {
                    BinOp::Add => "add",
                    BinOp::Sub => "sub",
                    BinOp::Mul => "imul",
                    BinOp::Div => "idiv",
                };
                if op == BinOp::Div {
                    format!(
                        "    mov eax, {}\n    mov ebx, {}\n    mov edx, 0\n    idiv ebx\n    mov {}, eax\n",
                        left_mangled, right_mangled, dest_mangled
                    )
                } else if op == BinOp::Mul {
                    format!("    mov eax, {}\n    imul {}, eax\n    mov {}, eax\n", left_mangled, right_mangled, dest_mangled)
                } else {
                    format!("    mov eax, {}\n    {} eax, {}\n    mov {}, eax\n", left_mangled, op_asm, right_mangled, dest_mangled)
                }
            }
            IRInst::Compare(dest, op, left, right) => {
                // Clone dest because we need it both for mangling and for the label name
                let dest_str = dest.clone();
                let dest_mangled = if dest.starts_with('t') { dest } else { self.mangle(&dest_str) };
                let left_mangled  = if left.starts_with('t')  { left } else { self.mangle(&left) };
                let right_mangled = if right.starts_with('t') { right } else { self.mangle(&right) };
                let (jump_op, _) = match op {
                    CompareOp::Less    => ("jl",  0),
                    CompareOp::Greater => ("jg",  0),
                };
                format!(
                    "    mov eax, {}\n    cmp eax, {}\n    mov {}, 0\n    {} L_cmp_{}\n    mov {}, 1\nL_cmp_{}:\n",
                    left_mangled, right_mangled, dest_mangled, jump_op, dest_str, dest_mangled, dest_str
                )
            }
            IRInst::DrawPixel(x, y, color) => {
                let x_mangled = if x.starts_with('t') { x } else { self.mangle(&x) };
                let y_mangled = if y.starts_with('t') { y } else { self.mangle(&y) };
                let c_mangled = if color.starts_with('t') { color } else { self.mangle(&color) };
                format!("    push {}\n    push {}\n    push {}\n    call DrawPixel_helper\n", x_mangled, y_mangled, c_mangled)
            }
            IRInst::DrawRect(x, y, w, h, color) => {
                let x_mangled = if x.starts_with('t') { x } else { self.mangle(&x) };
                let y_mangled = if y.starts_with('t') { y } else { self.mangle(&y) };
                let w_mangled = if w.starts_with('t') { w } else { self.mangle(&w) };
                let h_mangled = if h.starts_with('t') { h } else { self.mangle(&h) };
                let c_mangled = if color.starts_with('t') { color } else { self.mangle(&color) };
                format!("    push {}\n    push {}\n    push {}\n    push {}\n    push {}\n    call DrawRect_helper\n", 
                    x_mangled, y_mangled, w_mangled, h_mangled, c_mangled)
            }
            IRInst::ClearScreen => "    call ClrScr\n".to_string(),
            IRInst::Delay(ms) => {
                let ms_mangled = if ms.starts_with('t') { ms } else { self.mangle(&ms) };
                format!("    mov eax, {}\n    call Delay\n", ms_mangled)
            }
            IRInst::WaitKey => "    call ReadChar\n".to_string(),
            IRInst::Label(name) => format!("{}:\n", name),
            IRInst::Jump(target) => format!("    jmp {}\n", target),
            IRInst::JumpIfZero(cond, target) => {
                let cond_mangled = if cond.starts_with('t') { cond } else { self.mangle(&cond) };
                format!("    cmp {}, 0\n    je {}\n", cond_mangled, target)
            }
        }
    }
}